### ISSUE TITLE
Custom Color Scheme

### ISSUE THREAD

**Issue by lukeaus** [aziz/BetterFindBuffer#15]
Can't get custom colour theme to load in OSX with ST3 despite following instructions and multiple ST3 restarts

**Comment by NerOcrO** [comment]
Me too on Ubuntu/ST3 :(

**Comment by simonvizzini** [comment]
I'm having the same problem on Windows. I'm no ST3 expert, never wrote a plugin or even coded in Python, but by taking a look at the `find_results.py` file:

````
# Some plugins like **Color Highlighter** are forcing their color-scheme to the activated view
# Although, it's something that should be fixed on their side, in the meantime, it's safe to force
# the color shceme on `on_activated_async` event.
class BFBForceColorSchemeCommand(sublime_plugin.EventListener):
    def on_activated_async(self, view):
        syntax = view.settings().get('syntax')
        if syntax and (syntax.endswith("Find Results.hidden-tmLanguage")):
            view.settings().set('color_scheme','Packages/BetterFindBuffer/FindResults.hidden-tmTheme')
````

If I understand it correctly, this plugin will always apply the color scheme from `Packages/BetterFindBuffer/FindResults.hidden-tmTheme` as soon as the find window gets activated?

I was only able to change the color scheme by editing the tmTheme file in `Packages/BetterFindBuffer/FindResults.hidden-tmTheme` but of course that is not a nice solution.

**Comment by NerOcrO** [comment]
There is a solution more correct.
Change this line:
```php
if syntax and (syntax.endswith("Find Results.hidden-tmLanguage")):
```
by
```php
if syntax and (syntax.endswith("Find Results.hidden-tmTheme")):
```
And follow the documentation!

**Comment by a-dg** [comment]
@NerOcrO This worked great for me! Would you consider submitting a pull request?
